### ISSUE TITLE
[Bug]: New-PSWorkItem failure with -PassThru

### ISSUE THREAD

**Issue by jbelina** [jdhitsolutions/PSWorkItem#5]
### Describe the problem

When creating a new task using the -PassThru feature, the path is not passed into _newWorkItem resulting in the following error calling Convert-Path.

PS> New-PSWorkItem -Category work -Name "still testing" -Passthru -Debug -Verbose | Format-List

> Error Message:
> DEBUG: [23:02:02.9422279 _newWorkItem] Creating item 'still testing' [0f3664f3-be5a-4609-94fa-268d96928d1a]
> Convert-Path: C:\...\PowerShell\Modules\PSWorkItem\0.8.0\functions\private\helpers.ps1:18
> Line |
>   18 |      $item.path = Convert-Path $path
>      |                                ~~~~~
>      | Cannot bind argument to parameter 'Path' because it is an empty string.

### Expectation

The new task should be passed through to the pipeline without error.

### Additional Information

This issue is new to v0.8.0 due to the change in _newWorkItem and affects both New-PSWorkItem and Complete-PSWorkItem

(I have a fix ready and tested.)

### PowerShell version

7.2

### Platform

Windows 11 Home

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [X] You are running PowerShell in an elevated session.
- [X] You are running in a traditional PowerShell console or Windows Terminal

**Comment by jdhitsolutions** [comment]
I get the same error.

**Comment by jdhitsolutions** [comment]
PR merged. This will be added in v0.9.0.
